### ISSUE TITLE
clang-16: ASan fails for `memBufTest`.

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1753]
As part of #1713 I encountered an address sanitizer issue with clang-14. This doesn't happen with clang-13 (tested locally). Error message:

```
30: Test command: /home/runner/work/alpaka/alpaka/build/test/unit/mem/buf/memBufTest "--colour-mode" "default"
30: Test timeout computed to be: 1500
30: =================================================================
30: ==10579==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new vs free) on 0x60700000ddf0
30:     #0 0x5570bd780102 in __interceptor_free (/home/runner/work/alpaka/alpaka/build/test/unit/mem/buf/memBufTest+0xf4102) (BuildId: dbbfef11bf08aba8be17c096a1867d9632ca5f95)
30:     #1 0x7f64a009e25d in std::invalid_argument::~invalid_argument() (/usr/lib/llvm-14/lib/libc++abi.so.1+0x2425d) (BuildId: 9e9a6e2998ed7d6781edcc2eb856fba4529c1f05)
30:     #2 0x7f64a00a05d3 in __cxa_end_catch (/usr/lib/llvm-14/lib/libc++abi.so.1+0x265d3) (BuildId: 9e9a6e2998ed7d6781edcc2eb856fba4529c1f05)
30:     #3 0x5570bd8f8895 in void testBufferAccessorAdaptor<alpaka::AccCpuSerial<std::__1::integral_constant<unsigned long, 1ul>, unsigned long> >(alpaka::Vec<alpaka::trait::DimType<alpaka::AccCpuSerial<std::__1::integral_constant<unsigned long, 1ul>, unsigned long>, void>::type, alpaka::trait::IdxType<alpaka::AccCpuSerial<std::__1::integral_constant<unsigned long, 1ul>, unsigned long>, void>::type> const&, alpaka::Vec<alpaka::trait::DimType<alpaka::AccCpuSerial<std::__1::integral_constant<unsigned long, 1ul>, unsigned long>, void>::type, alpaka::trait::IdxType<alpaka::AccCpuSerial<std::__1::integral_constant<unsigned long, 1ul>, unsigned long>, void>::type> const&) /home/runner/work/alpaka/alpaka/test/unit/mem/buf/src/BufTest.cpp:268:9
30:     #4 0x5570bd8f8895 in void CATCH2_INTERNAL_TEMPLATE_TEST_25<alpaka::AccCpuSerial<std::__1::integral_constant<unsigned long, 1ul>, unsigned long> >() /home/runner/work/alpaka/alpaka/test/unit/mem/buf/src/BufTest.cpp:280:5
30:     #5 0x5570bdc39ff9 in Catch::TestInvokerAsFunction::invoke() const /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/internal/catch_test_case_registry_impl.cpp:149:9
30:     #6 0x5570bdc0d724 in Catch::TestCaseHandle::invoke() const /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/../catch2/catch_test_case_info.hpp:114:24
30:     #7 0x5570bdc0d724 in Catch::RunContext::invokeActiveTestCase() /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/internal/catch_run_context.cpp:503:27
30:     #8 0x5570bdc0d724 in Catch::RunContext::runCurrentTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/internal/catch_run_context.cpp:473:17
30:     #9 0x5570bdc0c469 in Catch::RunContext::runTest(Catch::TestCaseHandle const&) /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/internal/catch_run_context.cpp:238:13
30:     #10 0x5570bdc1eddb in Catch::(anonymous namespace)::TestGroup::execute() /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/catch_session.cpp:112:45
30:     #11 0x5570bdc1d21a in Catch::Session::runInternal() /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/catch_session.cpp:334:39
30:     #12 0x5570bdc1bf8d in Catch::Session::run() /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/catch_session.cpp:265:24
30:     #13 0x5570bdbc079a in int Catch::Session::run<char>(int, char const* const*) /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/../catch2/catch_session.hpp:41:30
30:     #14 0x5570bdbc079a in main /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/internal/catch_main.cpp:36:29
30:     #15 0x7f649fd17082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
30:     #16 0x5570bd6fdc9d in _start (/home/runner/work/alpaka/alpaka/build/test/unit/mem/buf/memBufTest+0x71c9d) (BuildId: dbbfef11bf08aba8be17c096a1867d9632ca5f95)
30: 
30: 0x60700000ddf0 is located 0 bytes inside of 80-byte region [0x60700000ddf0,0x60700000de40)
30: allocated by thread T0 here:
30:     #0 0x5570bd7bb17d in operator new(unsigned long) (/home/runner/work/alpaka/alpaka/build/test/unit/mem/buf/memBufTest+0x12f17d) (BuildId: dbbfef11bf08aba8be17c096a1867d9632ca5f95)
30:     #1 0x7f64a010ae6e in std::logic_error::logic_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (/usr/lib/llvm-14/lib/libc++.so.1+0x4ee6e) (BuildId: 235be0020fe75600ed00dd45b9e3ba575638cf40)
30:     #2 0x5570bd8f8242 in void testBufferAccessorAdaptor<alpaka::AccCpuSerial<std::__1::integral_constant<unsigned long, 1ul>, unsigned long> >(alpaka::Vec<alpaka::trait::DimType<alpaka::AccCpuSerial<std::__1::integral_constant<unsigned long, 1ul>, unsigned long>, void>::type, alpaka::trait::IdxType<alpaka::AccCpuSerial<std::__1::integral_constant<unsigned long, 1ul>, unsigned long>, void>::type> const&, alpaka::Vec<alpaka::trait::DimType<alpaka::AccCpuSerial<std::__1::integral_constant<unsigned long, 1ul>, unsigned long>, void>::type, alpaka::trait::IdxType<alpaka::AccCpuSerial<std::__1::integral_constant<unsigned long, 1ul>, unsigned long>, void>::type> const&) /home/runner/work/alpaka/alpaka/test/unit/mem/buf/src/BufTest.cpp:268:9
30:     #3 0x5570bd8f8242 in void CATCH2_INTERNAL_TEMPLATE_TEST_25<alpaka::AccCpuSerial<std::__1::integral_constant<unsigned long, 1ul>, unsigned long> >() /home/runner/work/alpaka/alpaka/test/unit/mem/buf/src/BufTest.cpp:280:5
30:     #4 0x5570bdc39ff9 in Catch::TestInvokerAsFunction::invoke() const /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/internal/catch_test_case_registry_impl.cpp:149:9
30:     #5 0x5570bdc0d724 in Catch::TestCaseHandle::invoke() const /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/../catch2/catch_test_case_info.hpp:114:24
30:     #6 0x5570bdc0d724 in Catch::RunContext::invokeActiveTestCase() /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/internal/catch_run_context.cpp:503:27
30:     #7 0x5570bdc0d724 in Catch::RunContext::runCurrentTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/internal/catch_run_context.cpp:473:17
30:     #8 0x5570bdc0c469 in Catch::RunContext::runTest(Catch::TestCaseHandle const&) /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/internal/catch_run_context.cpp:238:13
30:     #9 0x5570bdc1eddb in Catch::(anonymous namespace)::TestGroup::execute() /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/catch_session.cpp:112:45
30:     #10 0x5570bdc1d21a in Catch::Session::runInternal() /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/catch_session.cpp:334:39
30:     #11 0x5570bdc1bf8d in Catch::Session::run() /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/catch_session.cpp:265:24
30:     #12 0x5570bdbc079a in int Catch::Session::run<char>(int, char const* const*) /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/../catch2/catch_session.hpp:41:30
30:     #13 0x5570bdbc079a in main /home/runner/work/alpaka/alpaka/build/thirdParty/catch2/src/./src/catch2/internal/catch_main.cpp:36:29
30:     #14 0x7f649fd17082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
30: 
30: SUMMARY: AddressSanitizer: alloc-dealloc-mismatch (/home/runner/work/alpaka/alpaka/build/test/unit/mem/buf/memBufTest+0xf4102) (BuildId: dbbfef11bf08aba8be17c096a1867d9632ca5f95) in __interceptor_free
30: ==10579==HINT: if you don't care about these errors you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
30: ==10579==ABORTING
30/42 Test #30: memBufTest .......................***Failed    2.75 sec
```

The error points to this line of code:

https://github.com/alpaka-group/alpaka/blob/dd3352be8ff9e862cdfb3ad2495e3de5fece1be5/test/unit/mem/buf/src/BufTest.cpp#L266-L268

This leads me to believe that this is a bug in either Catch2 or LLVM. I'm waiting for my distribution to roll out llvm-14; until then I will disable the ASan for this specific test case.

**Comment by j-stephan** [comment]
So this doesn't happen with my local clang-14 v14.0.6. But it now appears in our CI for #1872 for clang v13.0.1. I wonder whether this is a platform difference or if clang 13.0.1 introduced a regression that was fixed in some minor v14 release...

**Comment by j-stephan** [comment]
This seems to be a bug in the official LLVM libc++ packages for Ubuntu: https://github.com/llvm/llvm-project/issues/59432. We will switch to libstdc++ until it is resolved.

**Comment by bernhardmgruber** [comment]
I just ran clang-16 with ASan and `memBufTest` passed without issues. @j-stephan can we close this issue? I don't care about old compilers having ASan bugs :)

**Comment by j-stephan** [comment]
We should update the `ASan` job to clang-16 and switch back to `libc++`. Then we can close this.

**Comment by bernhardmgruber** [comment]
The issue persists with `clang-16` in the CI, but works locally.

**Comment by j-stephan** [comment]
Is `locally` an Ubuntu installation with the packages from the LLVM apt repository?

**Comment by bernhardmgruber** [comment]
> Is locally an Ubuntu installation with the packages from the LLVM apt repository?

I think so. I can check when I am back in the office (teleworking).

Edit: yes, Ubuntu 23.04 with clang-16.0.3 via the LLVM apt repo.

Also thanks for reopening the issue!
